### PR TITLE
Add my mods and myself

### PR DESCRIPTION
**Pull request by jae1911**
- [x] The mod id matches the harmony id if used by the mod and starts with the same id as your author folder
- [x] All used links are valid
- [x] Your ResoniteMod.Version must match the version being added in the manifest
- [x] Your AssemblyVersion should match the mod version
- [x] You have included an accurate `sha256` hash for each artifact
- [x] Do not remove old mods. Instead, use the `deprecated` flag
- [x] Follow the [Resonite Policies and Guidelines](https://resonite.com/policies/) and [Mod Submission Guidelines](https://github.com/resonite-modding-group/resonite-mod-manifest/wiki/Submission-Guidelines)

### CODE REVIEW

**Comment by XDelta** [comment]
Preferably just add the latest version of the mod.

**Comment by jae1911** [comment]
This should be ready now

**Comment by XDelta** [comment]
Should be incremented to a 1.0.8

**Comment by jae1911** [comment]
There you go, this should have proper semver.

**Comment by jae1911** [comment]
Just noticed the AssemblyFileVersion wasn't updated correctly, sorry about that.
I'll do a release later that pushes some actual features.

**Comment by jae1911** [comment]
There we go, everything should be correct now.

Sorry for the messs.

**Comment by XDelta** [comment]
No worries

**Review by XDelta — APPROVED** [review]

**Pull request merged**
