### PR TITLE
Updated CherryPick to v1.1.0

### PR DESCRIPTION
**Pull request by SectOLT**
Updated CherryPick to v1.1.0

### CODE REVIEW

**Review by XDelta — APPROVED** [review]

**Comment by XDelta** [comment]
Additional note that [assembly: AssemblyVersion("1.1.0.0")] and [assembly: AssemblyFileVersion("1.1.0")] should 'match'

**Comment by SectOLT** [comment]
> Additional note that [assembly: AssemblyVersion("1.1.0.0")] and [assembly: AssemblyFileVersion("1.1.0")] should 'match'

Strange, the AssemblyFileVersion should be set according to the version obtained from AssemblyVersion which is defined in the csproj. If that is not the case, Cyro made a mistake. I was not even aware the file properties showed a different assembly version.

**Comment by XDelta** [comment]
Actually looks like more a result of the build process changing this anyway.. even if it is set as 3 section, seems to write it as 4 anyway. Although it is more visibly apparent because of their `Assembly.GetName().Version.ToString();` will grab that instead of showing the `1.1.0` form.

**Comment by SectOLT** [comment]
On file it might show as 4 numbers, but it doesn't looks like it's causing much issues as long as people still see in manifest and in assembly that the version matches. I think.

**Comment by XDelta** [comment]
Shouldn't be an issue, but may be a suggestion for their version string to not use that method of grabbing the version. Instead going the other direction of using the Version string to set the assembly attributes.

**Comment by SectOLT** [comment]
Good point. I'll escalate an issue to let them know.

**Comment by XDelta** [comment]
An example is shown in https://github.com/resonite-modding-group/ExampleMod/blob/main/ExampleMod/ExampleMod.cs setting the attributes from a version constant, although it looks like they set the version in their csproj instead

**Comment by XDelta** [comment]
Not sure offhand which ways get both to be set 'correctly' but this atleast shows the 'Version' string as `1.1.0`

**Comment by SectOLT** [comment]
Well, the constant way does sounds more handy, but yeah, they set it in csproj, then used `$(version)` to define the AssemblyVersion, then `Assembly.GetName().Version.ToString();` in the cs file took the version from the Assembly but decided to parse it as 4 numbers instead of its written 3.

**Comment by SectOLT** [comment]
We'll see if he changes it, getting matching numbers is important, though in this particular case it at least doesn't break the mod.

**Pull request merged**
